version: "3.8"
services:
  service-sap-builder:
    build: .
    container_name: sap-builder-backend
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "7777:3000"
    volumes:
      - ./projects:/home/node/app/projects:rw
      - ./templates:/home/node/app/templates:ro
      - /var/run/docker.sock:/var/run/docker.sock  # ← Importante!
    restart: unless-stopped
    networks:
      - sap-builder-network

networks:
  sap-builder-network:
    driver: bridge
