services:
  sapui5-menu-app:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    ports:
      - "8006:8081"
    volumes:
      - ./webapp:/home/node/app/webapp:delegated   # <-- só o fonte
      - sapui5-menu_node_modules:/home/node/app/node_modules  # persiste deps dentro do contêiner
    networks:
      - sapui5-menu-network

volumes:
  sapui5-menu_node_modules:

networks:
  sapui5-menu-network:
    driver: bridge
